
const employees = [
     {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare Sales Report",
        taskDescription: "Prepare the monthly sales report.",
        taskDate: "2026-07-18",
        category: "Sales",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Client Meeting",
        taskDescription: "Attend meeting with the client.",
        taskDate: "2026-07-15",
        category: "Meetings",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Update CRM",
        taskDescription: "Update customer records in CRM.",
        taskDate: "2026-07-19",
        category: "Management",
      },
    ],
  },

  {
    id: 2,
    firstName: "Vivaan",
    email: "employee2@example.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Fix Login Bug",
        taskDescription: "Resolve authentication issue.",
        taskDate: "2026-07-18",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Code Review",
        taskDescription: "Review teammate's pull request.",
        taskDate: "2026-07-14",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Deploy API",
        taskDescription: "Deploy backend API to production.",
        taskDate: "2026-07-16",
        category: "Deployment",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Write Unit Tests",
        taskDescription: "Increase code coverage.",
        taskDate: "2026-07-20",
        category: "Testing",
      },
    ],
  },

  {
    id: 3,
    firstName: "Arjun",
    email: "employee3@example.com",
    password: "123",
    taskNumber: {
      active: 3,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Homepage",
        taskDescription: "Create homepage wireframes.",
        taskDate: "2026-07-18",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Logo Revision",
        taskDescription: "Update company logo.",
        taskDate: "2026-07-12",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Create Icons",
        taskDescription: "Design dashboard icons.",
        taskDate: "2026-07-21",
        category: "UI",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Banner Design",
        taskDescription: "Prepare marketing banner.",
        taskDate: "2026-07-17",
        category: "Marketing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Prototype App",
        taskDescription: "Build interactive prototype.",
        taskDate: "2026-07-22",
        category: "UX",
      },
    ],
  },
    {
    id: 4,
    firstName: "Aditya",
    email: "employee4@example.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Database Backup",
        taskDescription: "Perform weekly backup.",
        taskDate: "2026-07-18",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Optimize Queries",
        taskDescription: "Improve SQL performance.",
        taskDate: "2026-07-15",
        category: "Database",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Monitor Server",
        taskDescription: "Check server health.",
        taskDate: "2026-07-19",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Migration",
        taskDescription: "Migrate old database.",
        taskDate: "2026-07-13",
        category: "Database",
      },
    ],
  },

  {
    id: 5,
    firstName: "Rohan",
    email: "employee5@example.com",
    password: "123",
    taskNumber: {
      active: 4,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Recruit Developer",
        taskDescription: "Conduct technical interviews.",
        taskDate: "2026-07-18",
        category: "HR",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Employee Onboarding",
        taskDescription: "Complete onboarding process.",
        taskDate: "2026-07-11",
        category: "HR",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Payroll Review",
        taskDescription: "Verify monthly payroll.",
        taskDate: "2026-07-20",
        category: "Finance",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Training Session",
        taskDescription: "Organize employee training.",
        taskDate: "2026-07-16",
        category: "HR",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Policy Update",
        taskDescription: "Revise leave policy.",
        taskDate: "2026-07-23",
        category: "Administration",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Attendance Audit",
        taskDescription: "Review attendance records.",
        taskDate: "2026-07-24",
        category: "HR",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    firstName: "Admin",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees")) || [];
  const admin = JSON.parse(localStorage.getItem("admin")) || [];

  return { employees, admin };
};